
-- Explorando e entendendo os dados

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_PRODUCT_CATEGORY]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_CUSTOMERS]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_GEOLOCATION]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDER_ITEMS]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDER_PAYMENTS]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDERS]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_PRODUCTS]
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_SALLERS]

----------------------------------
-- Transformando em Tabalas Fact
----------------------------------

-- 1. Tabela CUSTOMERS
SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_CUSTOMERS]

create table TB_ACT_OLIST_CUSTOMERS
(
	CUSTOMER_ID					NVARCHAR(150),
	CUSTOMER_UNIQUE_ID			NVARCHAR(150),
	CUSTOMER_ZIP_CODE_PREFIX	NVARCHAR(15),
	CUSTOMER_CITY				NVARCHAR(100),
	CUSTOMER_STATE				CHAR(2)
)

INSERT INTO TB_ACT_OLIST_CUSTOMERS			-- Fusão dos dados	
SELECT * FROM [dbo].[TB_CG_OLIST_CUSTOMERS]

SELECT * FROM TB_ACT_OLIST_CUSTOMERS -- Verificando as alterações


-- 2. Tabela ORDER ITEMS

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDER_ITEMS]

create table TB_ACT_OLIST_ORDER_ITEMS
(
	ORDER_ID				NVARCHAR(150),
	ORDER_ITEM_ID			INT,
	PRODUCT_ID				NVARCHAR(150),
	SELLER_ID				NVARCHAR(150),
	SHIPPING_LIMIT_DATE		DATETIME,		-- Apresentou erro na alteração do data type
	PRICE					DECIMAL(12,2),
	FREIGHT_VALUE			DECIMAL(12,2)					
)

INSERT INTO TB_ACT_OLIST_ORDER_ITEMS			-- resultou em erro devido ao tipo de dado de uma coluna
SELECT * FROM [dbo].[TB_CG_OLIST_ORDER_ITEMS]
SELECT * FROM TB_ACT_OLIST_ORDER_ITEMS

-- Resolvendo o erro
exec sp_help TB_CG_OLIST_ORDER_ITEMS -- revisando os tipos

-- Identificas registros errados

SELECT shipping_limit_date 
FROM TB_CG_OLIST_ORDER_ITEMS
WHERE TRY_CONVERT(DATETIME, shipping_limit_date, 120) IS NULL;

-- Inserido os dados corretamente

INSERT INTO TB_ACT_OLIST_ORDER_ITEMS (ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, 
SELLER_ID, SHIPPING_LIMIT_DATE, PRICE, FREIGHT_VALUE)
SELECT ORDER_ID, ORDER_ITEM_ID, PRODUCT_ID, SELLER_ID, 
       TRY_CONVERT(DATETIME, shipping_limit_date, 120), -- Conversão segura
       PRICE, FREIGHT_VALUE
FROM [dbo].[TB_CG_OLIST_ORDER_ITEMS];

SELECT * FROM TB_ACT_OLIST_ORDER_ITEMS

-- 3. Tabela ORDER PAYMENTS

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDER_PAYMENTS]

create table TB_ACT_ORDER_PAYMENTS
(
	ORDER_ID				NVARCHAR(150),
	PAYMENT_SEQUENTIAL		INT,
	PAYMENT_TYPE			NVARCHAR(150),
	PAYMENT_INSTALLMENTS	INT,
	PAYMENT_VALUE			DECIMAL(12,2)
)

SELECT * FROM TB_ACT_ORDER_PAYMENTS

INSERT INTO TB_ACT_ORDER_PAYMENTS
SELECT *FROM [dbo].[TB_CG_OLIST_ORDER_PAYMENTS]

-- 4. Tabela ORDERS

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_ORDERS]
EXEC sp_help TB_CG_OLIST_ORDERS

create table TB_ACT_OLIST_ORDERS
(
	ORDER_ID						NVARCHAR(150),
	CUSTUMER_ID						NVARCHAR(150),
	ORDER_STATUS					NVARCHAR(100),
	ORDER_PURCHASE_TIMESTAMP		DATETIME,		-- Apresentou erro na alteração do data type
	ORDER_APPROVED_AT				DATETIME,
	ORDER_DELIVERED_CARRIER_DATE	DATETIME,
	ORDER_DELIVERED_CUSTOMER_DATE	DATETIME,
	ORDER_ESTIMATED_DELIVERY_DATE	DATETIME
)
SELECT * FROM TB_ACT_OLIST_ORDERS

EXEC sp_rename 'TB_ACT_OLIST_ORDERS.CUSTUMER_ID', 'CUSTOMER_ID', 'COLUMN'; -- Corrigindo nome da coluna

SELECT shipping_limit_date 
FROM TB_CG_OLIST_ORDER_ITEMS
WHERE TRY_CONVERT(DATETIME, shipping_limit_date, 120) IS NULL;

INSERT INTO TB_ACT_OLIST_ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_STATUS, ORDER_PURCHASE_TIMESTAMP, ORDER_APPROVED_AT, 
ORDER_DELIVERED_CARRIER_DATE, ORDER_DELIVERED_CUSTOMER_DATE, ORDER_ESTIMATED_DELIVERY_DATE)
SELECT ORDER_ID, CUSTOMER_ID, ORDER_STATUS,
	TRY_CONVERT (datetime, ORDER_PURCHASE_TIMESTAMP, 120),
	TRY_CONVERT (datetime, ORDER_APPROVED_AT, 120), 
	TRY_CONVERT	(datetime, ORDER_DELIVERED_CARRIER_DATE, 120),
	TRY_CONVERT (datetime, ORDER_DELIVERED_CUSTOMER_DATE, 120),
	TRY_CONVERT (datetime, ORDER_ESTIMATED_DELIVERY_DATE, 120)
FROM [dbo].[TB_CG_OLIST_ORDERS]

-- 5. Tabela PRODUCT CATEGORY

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_PRODUCT_CATEGORY]

create table TB_ACT_PRODUCT_CATEGORY
(
	PRODUCT_CATEOGRY_NAME			NVARCHAR(150),
	PRODUCT_CATEGORY_NAME_ENGLISH	NVARCHAR(150)
)

SELECT * FROM TB_ACT_PRODUCT_CATEGORY

INSERT INTO TB_ACT_PRODUCT_CATEGORY
SELECT * FROM [dbo].[TB_CG_OLIST_PRODUCT_CATEGORY]

-- 6. Tabela ORDER PRODUCTS 

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_PRODUCTS]
exec sp_help TB_CG_OLIST_PRODUCTS

create table TB_ACT_PRODUCTS
(
	PRODUCT_ID						NVARCHAR(150),
	PRODUCT_CATEGORY_NAME			NVARCHAR(50),
	PRODUCT_NAME_LENGHT				FLOAT,
	PRODUCT_DESCRIPTION_LENGHT		FLOAT,
	PRODUCT_PHOTOS_QTY				FLOAT,
	PRODUCT_WEIGHT_G				DECIMAL(10,2),
	PRODUCT_LENGTH_CM				DECIMAL(10,2),
	PRODUCT_HEIGHT_CM				DECIMAL(10,2),
	PRODUCT_WIDTH_CM				DECIMAL(10,2)
)
SELECT * FROM TB_ACT_PRODUCTS

INSERT INTO TB_ACT_PRODUCTS					-- Erro ao converter valor de texto (varchar) em um tipo numérico 
SELECT * FROM [dbo].[TB_CG_OLIST_PRODUCTS]

-- Resolvento o Erro

INSERT INTO TB_ACT_PRODUCTS
SELECT 
    PRODUCT_ID, PRODUCT_CATEGORY_NAME, PRODUCT_NAME_LENGHT, PRODUCT_DESCRIPTION_LENGHT, PRODUCT_PHOTOS_QTY,
    TRY_CONVERT(DECIMAL(10,2), PRODUCT_WEIGHT_G),
    TRY_CONVERT(DECIMAL(10,2), PRODUCT_LENGTH_CM),
    TRY_CONVERT(DECIMAL(10,2), PRODUCT_HEIGHT_CM),
    TRY_CONVERT(DECIMAL(10,2), PRODUCT_WIDTH_CM)
FROM [dbo].[TB_CG_OLIST_PRODUCTS]
SELECT * FROM TB_ACT_PRODUCTS
EXEC sp_help TB_ACT_PRODUCTS

-- 7. Tabela SALLERS

SELECT TOP 10 * FROM [dbo].[TB_CG_OLIST_SALLERS]
exec sp_help TB_CG_OLIST_SALLERS

create table TB_ACT_OLIST_SALLERS
(
	SELLER_ID					NVARCHAR(150),
	SELLER_ZIP_CODE_PREFIX		INT,
	SELLER_CITY					NVARCHAR(150),
	SELLER_STATE				CHAR(2)
)

SELECT * FROM TB_ACT_OLIST_SALLERS

INSERT INTO TB_ACT_OLIST_SALLERS
SELECT * FROM [dbo].[TB_CG_OLIST_SALLERS]